### ISSUE TITLE
random feedback

### ISSUE THREAD

**Issue by cgwalters** [jdoss/atomic-wireguard#1]
First, thanks for writing this!  It's useful to have a concrete reference point.

One high level choice to make with 3rd party kernel modules is: Do you want to block upgrades if they won't compile?  The DKMS model answers "no".  It looks like you're trying to do a similar thing.

However, we could make it possible to insert arbitrary hooks into the `rpm-ostree upgrade` path, including ones that ran containers that had access to the new root.  We actually do a tiny "sanity check" today: https://github.com/projectatomic/rpm-ostree/blob/bff3a54e1ee67398bd7a2cfdc359326689479954/src/libpriv/rpmostree-scripts.c#L902
It'd be possible to extend that to do something like your wireguard container build, and in there download the buildroot necessary for the *new* kernel.

The end semantic would be that typing `rpm-ostree upgrade` would fail if the wireguard module couldn't be built for the new target kernel.

Presumably for you, wireguard is a critical path function.  Are you thinking you'd do a rollback now if this fails?

**Comment by jdoss** [comment]
My goal with this project was to initially model after DKMS as much as possible. While WireGuard is used as a VPN tunnel and not having it start on boot could be problematic, I am not sure we would want to dictate one way or another to end users for every kernel module use case. Giving them the choice to fit their use case, rollback or to fully boot so they can fix the problem would be ideal. 

For some people having WireGuard fail to compile correctly is a big deal because their remote endpoint could be at risk if you reboot without it working. Other kernel modules, such as [ipt-netflow](https://copr.fedorainfracloud.org/coprs/jdoss/ipt-netflow/) it might be acceptable for it to be broken for a time as they can still access the instance to figure out what broke. 

I do think if we could tie kernel modules being built into the upgrade process, so you can get the failure feedback before you reboot would be amazing.
